// plugins/pasteboard-pro/apps/atools/src/components/Toolbar.svelte
<script lang="ts">
  let { query, paused, compact, status, syncState, loading, onquery, ontogglepause, ontogglecompact, onsync, onaddstack, onsettings, oncreate }: {
    query: string; paused: boolean; compact: boolean; status: string; syncState: string; loading: boolean;
    onquery: (value: string) => void; ontogglepause: () => void; ontogglecompact: () => void;
    onsync: () => void; onaddstack: () => void; onsettings: () => void; oncreate: () => void;
  } = $props();
</script>

<header class="toolbar">
  <div class="brand"><span class="mark">P</span><div><strong>PasteboardPro</strong><small>{status}</small></div></div>
  <label class="search">
    <span aria-hidden="true">⌕</span>
    <input data-pb-search type="search" value={query} placeholder="搜索内容、App、日期或 Pinboard" autocomplete="off" oninput={(event) => onquery(event.currentTarget.value)} />
    <kbd>⌘F</kbd>
  </label>
  <div class="actions">
    <button type="button" onclick={oncreate} title="新建文本（Command-N）"><span>＋</span><em>新建</em></button>
    <button type="button" onclick={onsettings} title="隐私与历史保留"><span>⚙</span><em>设置</em></button>
    <button type="button" class:active={syncState === "syncing"} onclick={onsync} title="立即同步"><span>↻</span><em>{syncState === "success" ? "已同步" : "同步"}</em></button>
    <button type="button" onclick={onaddstack} title="加入 Paste Stack"><span>≋</span><em>Stack</em></button>
    <button type="button" aria-pressed={compact} onclick={ontogglecompact} title="切换紧凑模式"><span>↔</span><em>{compact ? "展开" : "紧凑"}</em></button>
    <button type="button" class:paused aria-pressed={paused} onclick={ontogglepause}><span>{paused ? "▶" : "Ⅱ"}</span><em>{paused ? "继续" : "暂停"}</em></button>
  </div>
</header>

<style>
  .toolbar { display:grid; grid-template-columns:auto minmax(240px, 520px) auto; gap:16px; align-items:center; min-height:68px; padding:12px 16px 10px; border-bottom:1px solid color-mix(in srgb, var(--pb-line) 72%, transparent); }
  .brand { display:flex; gap:10px; align-items:center; min-width:150px; }
  .mark { display:grid; width:30px; height:30px; border-radius:10px; background:linear-gradient(145deg,var(--pb-violet),#5145c4); box-shadow:0 7px 18px rgba(71,59,185,.32), inset 0 1px rgba(255,255,255,.42); color:white; font-size:13px; font-weight:800; place-items:center; }
  .brand div { display:grid; gap:2px; min-width:0; }
  strong { color:var(--pb-ink); font-size:12px; letter-spacing:-.01em; }
  small { max-width:160px; overflow:hidden; color:var(--pb-muted); font-size:9px; text-overflow:ellipsis; white-space:nowrap; }
  .search { display:grid; grid-template-columns:18px minmax(0,1fr) auto; gap:9px; align-items:center; height:40px; padding:0 11px; border:1px solid var(--pb-line); border-radius:14px; background:color-mix(in srgb,var(--pb-glass-strong) 68%,transparent); box-shadow:inset 0 1px rgba(255,255,255,.09); }
  .search:focus-within { outline:2px solid color-mix(in srgb,var(--pb-violet) 64%,transparent); outline-offset:2px; }
  .search > span { color:var(--pb-muted); font-size:20px; transform:rotate(-16deg); }
  input { min-width:0; border:0; outline:0; background:transparent; color:var(--pb-ink); font-size:12px; }
  input::placeholder { color:var(--pb-muted); }
  kbd { padding:2px 6px; border:1px solid var(--pb-line); border-radius:6px; color:var(--pb-muted); font-size:9px; }
  .actions { display:flex; gap:7px; justify-content:flex-end; }
  button { display:flex; gap:5px; align-items:center; min-height:34px; padding:0 10px; border:1px solid var(--pb-line); border-radius:11px; background:color-mix(in srgb,var(--pb-glass-strong) 62%,transparent); color:var(--pb-muted); cursor:pointer; }
  button:hover, button:focus-visible, button.active { color:var(--pb-ink); outline:2px solid color-mix(in srgb,var(--pb-violet) 45%,transparent); outline-offset:1px; }
  button.paused { color:var(--pb-coral); }
  button span { font-size:13px; } button em { font-size:10px; font-style:normal; }
  @media (max-width:760px) { .toolbar{grid-template-columns:auto minmax(0,1fr)} .actions{grid-column:1/-1} .actions button{flex:1;justify-content:center} .brand div{display:none} }
</style>

// plugins/pasteboard-pro/apps/ztools/src/components/Toolbar.vue
<script setup lang="ts">
import SearchBar from "./SearchBar.vue";

defineProps<{
  query: string;
  paused: boolean;
  compact: boolean;
}>();

const emit = defineEmits<{
  "update:query": [value: string];
  togglePause: [];
  toggleCompact: [];
  openSyncSettings: [];
  addStack: [];
  openPrivacySettings: [];
  createText: [];
}>();
</script>

<template>
  <header class="toolbar">
    <div class="brand" aria-label="PasteboardPro">
      <span class="brand__lens" aria-hidden="true"></span>
      <span>PasteboardPro</span>
    </div>
    <SearchBar :model-value="query" @update:model-value="emit('update:query', $event)" />
    <div class="toolbar__actions">
      <button type="button" class="tool-button" title="新建文本（Command-N）" @click="emit('createText')"><span aria-hidden="true">＋</span>新建</button>
      <button
        type="button"
        class="tool-button"
        title="隐私与历史保留"
        @click="emit('openPrivacySettings')"
      >
        <span aria-hidden="true">⚙</span>
        设置
      </button>
      <button
        type="button"
        class="tool-button"
        title="将选择加入 Paste Stack（Shift-Command-C）"
        @click="emit('addStack')"
      >
        <span aria-hidden="true">≋</span>
        Stack
      </button>
      <button
        type="button"
        class="tool-button"
        title="同步设置"
        @click="emit('openSyncSettings')"
      >
        <span aria-hidden="true">↻</span>
        同步
      </button>
      <button
        type="button"
        class="tool-button"
        :aria-pressed="compact"
        title="切换紧凑模式"
        @click="emit('toggleCompact')"
      >
        <span aria-hidden="true">↔</span>
        {{ compact ? "展开" : "紧凑" }}
      </button>
      <button
        type="button"
        class="tool-button"
        :class="{ 'tool-button--active': paused }"
        :aria-pressed="paused"
        @click="emit('togglePause')"
      >
        <span aria-hidden="true">{{ paused ? "▶" : "Ⅱ" }}</span>
        {{ paused ? "继续捕获" : "暂停捕获" }}
      </button>
    </div>
  </header>
</template>

<style scoped>
.toolbar {
  display: grid;
  grid-template-columns: auto minmax(260px, 520px) auto;
  gap: 16px;
  align-items: center;
  min-height: 62px;
  padding: 11px 16px;
  border-bottom: 1px solid var(--pb-line);
}

.brand {
  display: flex;
  gap: 10px;
  align-items: center;
  font-size: 13px;
  font-weight: 700;
  letter-spacing: -0.01em;
}

.brand__lens {
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: var(--pb-violet);
  box-shadow: 0 0 0 5px color-mix(in srgb, var(--pb-violet) 14%, transparent);
}

.toolbar__actions {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
}

.tool-button {
  display: flex;
  gap: 6px;
  align-items: center;
  min-height: 34px;
  padding: 0 11px;
  border: 1px solid var(--pb-line);
  border-radius: 11px;
  background: color-mix(in srgb, var(--pb-glass-strong) 60%, transparent);
  color: var(--pb-muted);
  cursor: pointer;
  font-size: 12px;
}

.tool-button:hover,
.tool-button:focus-visible {
  color: var(--pb-ink);
  outline: 2px solid color-mix(in srgb, var(--pb-violet) 56%, transparent);
  outline-offset: 1px;
}

.tool-button--active {
  background: color-mix(in srgb, #ffb65c 18%, var(--pb-glass-strong));
  color: #9b5410;
}

@media (max-width: 760px) {
  .toolbar {
    grid-template-columns: auto minmax(0, 1fr);
  }

  .brand span:last-child,
  .toolbar__actions .tool-button:nth-child(-n + 2) {
    display: none;
  }
}
</style>
